# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Checks

on:
  push:
    branches:
      - main
      - fix_missing_session_id
  pull_request:
    branches:
      - main
      - fix_missing_session_id
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_images:
    permissions: # required by the reusable workflow
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push-images.yaml
    with:
      push: true
      version: "dev"
